# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chip_Label',
            fields=[
                ('label', models.CharField(max_length=100)),
                ('lab', models.CharField(max_length=200)),
                ('cell_type', models.CharField(max_length=200)),
                ('replicate', models.IntegerField(default=-1)),
                ('accession', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chip_Seq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chr', models.CharField(max_length=6)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('peak', models.FloatField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc_snp.Chip_Label')),
            ],
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('name', models.CharField(max_length=400, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhenotypeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_val', models.FloatField()),
                ('log_score', models.FloatField()),
                ('phenotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc_snp.Phenotype')),
            ],
        ),
        migrations.CreateModel(
            name='R_Squared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.FloatField()),
                ('population', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SNP',
            fields=[
                ('chrom', models.CharField(max_length=6)),
                ('rs_id', models.CharField(default='unknown', max_length=200, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('phenotype', models.ManyToManyField(through='nc_snp.PhenotypeMap', to='nc_snp.Phenotype')),
                ('r_sq', models.ManyToManyField(through='nc_snp.R_Squared', to='nc_snp.SNP')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='r_squared',
            name='snp_A',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc_snp.SNP'),
        ),
        migrations.AddField(
            model_name='r_squared',
            name='snp_B',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snp_B', to='nc_snp.SNP'),
        ),
        migrations.AddField(
            model_name='phenotypemap',
            name='snp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc_snp.SNP'),
        ),
        migrations.AddField(
            model_name='phenotypemap',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nc_snp.Source'),
        ),
    ]
