# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc_snp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='r_squared',
            unique_together=set([('snp_A', 'snp_B', 'population')]),
        ),
    ]
